In [1]:
import pandas as pd 
import numpy as np

In [2]:
import matplotlib.pyplot as pyt 
import seaborn as sns

In [3]:
df = pd.read_csv("../data/diabetes.csv")

In [4]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [5]:
df.tail()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [6]:
df.shape

(100000, 9)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  str
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  str
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 8.0 MB

In [8]:
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [9]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 3854

In [11]:
print("Gender:")
print(df["gender"].value_counts())

print("\nSmoking History:")
print(df["smoking_history"].value_counts())

Gender:
gender
Female    58552
Male      41430
Other        18
Name: count, dtype: int64

Smoking History:
smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

In [12]:
print("Diabetes distribution:")
print(df["diabetes"].value_counts())

Diabetes distribution:
diabetes
0    91500
1     8500
Name: count, dtype: int64

In [13]:
print("\nDiabetes percentage:")
print(df["diabetes"].value_counts(normalize=True) * 100)

Diabetes percentage:
diabetes
0    91.5
1     8.5
Name: proportion, dtype: float64

In [14]:
#checking numerical range
numerical_columns = [
    "age",
    "bmi",
    "HbA1c_level",
    "blood_glucose_level"
]

df[numerical_columns].describe()

                 age            bmi    HbA1c_level  blood_glucose_level
count  100000.000000  100000.000000  100000.000000        100000.000000
mean       41.885856      27.320767       5.527507           138.058060
std        22.516840       6.636783       1.070672            40.708136
min         0.080000      10.010000       3.500000            80.000000
25%        24.000000      23.630000       4.800000           100.000000
50%        43.000000      27.320000       5.800000           140.000000
75%        60.000000      29.580000       6.200000           159.000000
max        80.000000      95.690000       9.000000           300.000000

In [15]:
print("Hypertension:")
print(df["hypertension"].value_counts())

print("\nHeart Disease:")
print(df["heart_disease"].value_counts())

Hypertension:
hypertension
0    92515
1     7485
Name: count, dtype: int64

Heart Disease:
heart_disease
0    96058
1     3942
Name: count, dtype: int64